import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, FindOptionsWhere, Like, Between } from 'typeorm';
import { ArticleEntity } from '../database/entities/article.entity';
import { CreateArticleDto } from './dto/create-article.dto';
import { UpdateArticleDto } from './dto/update-article.dto';
import { QueryArticleDto } from './dto/query-article.dto';
import { PaginatedResponse } from '@potential-unicorn/types';

@Injectable()
export class ArticlesService {
  constructor(
    @InjectRepository(ArticleEntity)
    private readonly articleRepository: Repository<ArticleEntity>,
  ) {}

  async create(createArticleDto: CreateArticleDto): Promise<ArticleEntity> {
    const article = this.articleRepository.create({
      ...createArticleDto,
      summary: '', // Will be generated by AI service
      highlights: [],
      tags: createArticleDto.tags || [],
      viewCount: 0,
      isTrending: false,
    });

    return this.articleRepository.save(article);
  }

  async findAll(
    query: QueryArticleDto,
  ): Promise<PaginatedResponse<ArticleEntity>> {
    const {
      category,
      language,
      sourceId,
      isTrending,
      dateFrom,
      dateTo,
      search,
      page = 1,
      limit = 10,
      sortBy = 'publishedAt',
      sortOrder = 'desc',
    } = query;

    const where: FindOptionsWhere<ArticleEntity> = {};

    if (category) where.category = category;
    if (language) where.language = language;
    if (sourceId) where.sourceId = sourceId;
    if (isTrending !== undefined) where.isTrending = isTrending;

    // Date range filter
    if (dateFrom && dateTo) {
      where.publishedAt = Between(new Date(dateFrom), new Date(dateTo));
    }

    // Search filter
    if (search) {
      // Note: This is a simple implementation. For production, consider using full-text search
      where.title = Like(`%${search}%`);
    }

    const [data, total] = await this.articleRepository.findAndCount({
      where,
      relations: ['source'],
      order: { [sortBy]: sortOrder.toUpperCase() },
      skip: (page - 1) * limit,
      take: limit,
    });

    const totalPages = Math.ceil(total / limit);

    return {
      data,
      pagination: {
        total,
        page,
        limit,
        totalPages,
        hasMore: page < totalPages,
      },
    };
  }

  async findOne(id: string): Promise<ArticleEntity> {
    const article = await this.articleRepository.findOne({
      where: { id },
      relations: ['source'],
    });

    if (!article) {
      throw new NotFoundException(`Article with ID ${id} not found`);
    }

    return article;
  }

  async update(
    id: string,
    updateArticleDto: UpdateArticleDto,
  ): Promise<ArticleEntity> {
    const article = await this.findOne(id);

    Object.assign(article, updateArticleDto);

    return this.articleRepository.save(article);
  }

  async remove(id: string): Promise<void> {
    const article = await this.findOne(id);
    await this.articleRepository.remove(article);
  }

  async incrementViewCount(id: string): Promise<ArticleEntity> {
    const article = await this.findOne(id);
    article.viewCount += 1;
    return this.articleRepository.save(article);
  }

  async findTrending(limit: number = 10): Promise<ArticleEntity[]> {
    return this.articleRepository.find({
      where: { isTrending: true },
      relations: ['source'],
      order: { viewCount: 'DESC' },
      take: limit,
    });
  }

  async findByCategory(
    category: string,
    limit: number = 10,
  ): Promise<ArticleEntity[]> {
    return this.articleRepository.find({
      where: { category: category as any },
      relations: ['source'],
      order: { publishedAt: 'DESC' },
      take: limit,
    });
  }
}
